"""empty message

Revision ID: 6cfa0c41ef09
Revises: 2c3ab1f93e09
Create Date: 2021-03-22 23:35:10.600888

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6cfa0c41ef09'
down_revision = '2c3ab1f93e09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('properties')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('prop_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('no_bed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('no_bath', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('loc', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('descr', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('media_addr', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('prop_id', name='properties_pkey')
    )
    # ### end Alembic commands ###
