"""empty message

Revision ID: b197bc0b8636
Revises: 9b77c1ea4018
Create Date: 2021-03-22 23:31:57.871032

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b197bc0b8636'
down_revision = '9b77c1ea4018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('properties')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('property_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('no_bed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('no_bath', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('desc', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('media_addr', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('property_id', name='properties_pkey')
    )
    # ### end Alembic commands ###
